### ISSUE TITLE
Email, phone number and location is not clickable on the contact screen.

### ISSUE THREAD

**Issue by iatharva** [Realocity/realocity.github.io#7]
Close this issue when resolved

**Comment by Realocity** [comment]
fixed :v)

**Comment by iatharva** [comment]
Still looks unclickable.

**Comment by Realocity** [comment]
You have to tap on "icon" not "text". Try again and let me know

**Comment by iatharva** [comment]
Yeah, but as a user, my first instinct would be to hover over the text and not the icon, which should be clickable.
But at the end of the day, it's up to you to decide.
